// See provided implementation integrated from the attached conversion.

export interface Bar { time: number; open: number; high: number; low: number; close: number; volume: number }
export type PocType = "+VWAP" | "-VWAP" | "+/-VWAP"
export interface VwapVolumeProfileInputs { period?: number; offset?: number; bins?: number; pocType?: PocType }
export interface ProfileBin { index:number; priceLow:number; priceHigh:number; volumeSigned:number; volumeTotal:number; gradientRatio:number; isUp:boolean }
export interface PocBox { priceLow:number; priceHigh:number; label:string; volumeTotal:number }
export interface VwapVolumeProfileResult { vwapSeries:(number|null)[]; vwapColor:("up"|"down"|null)[]; range:{high:number;low:number;step:number}; bins:ProfileBin[]; positivePoc:PocBox|null; negativePoc:PocBox|null; anchorIndex:number; noVolumeData:boolean }
const dayKey=(time:number)=>Math.floor(time/86400)
function computeSessionVwap(bars:Bar[]){const out:(number|null)[]=Array(bars.length).fill(null);let pv=0,v=0,day:number|null=null;for(let i=0;i<bars.length;i++){const b=bars[i],d=dayKey(b.time);if(d!==day){day=d;pv=0;v=0}const p=(b.high+b.low+b.close)/3;pv+=p*b.volume;v+=b.volume;out[i]=v>0?pv/v:null}return out}
const highest=(bars:Bar[],end:number,len:number,field:"high"|"low"|"volume")=>{const start=Math.max(0,end-len+1);let value=field==="low"?Infinity:-Infinity;for(let i=start;i<=end;i++)value=field==="low"?Math.min(value,bars[i][field]):Math.max(value,bars[i][field]);return value}
export function computeVwapVolumeProfile(bars:Bar[],inputs:VwapVolumeProfileInputs={}):VwapVolumeProfileResult{const period=Math.max(1,inputs.period??250),offset=inputs.offset??10,bins=Math.max(1,inputs.bins??50),pocType=inputs.pocType??"+/-VWAP",vwapSeries=computeSessionVwap(bars),last=bars.length-1,vwapColor=vwapSeries.map((v,i)=>i<5||v==null||vwapSeries[i-5]==null?null:v>vwapSeries[i-5]! ? "up":"down");if(last<0)return {vwapSeries,vwapColor,range:{high:0,low:0,step:0},bins:[],positivePoc:null,negativePoc:null,anchorIndex:0,noVolumeData:true};const H=highest(bars,last,period,"high"),L=highest(bars,last,period,"low"),step=(H-L)/bins||1,start=Math.max(0,last-period+1),signed=bars.map(()=>0);for(let i=start;i<=last;i++){const max=highest(bars,i,1000,"volume")||1;const up=vwapSeries[i]!=null&&vwapSeries[i-2]!=null?vwapSeries[i]!>vwapSeries[i-2]!:true;signed[i]=(up?bars[i].volume:-bars[i].volume)/max*20}const sums=Array.from({length:bins},()=>0),totals=Array.from({length:bins},()=>0);for(let i=start;i<=last;i++){const value=vwapSeries[i];if(value==null)continue;const index=Math.max(0,Math.min(bins-1,Math.floor((value-L)/step)));sums[index]+=signed[i];totals[index]+=bars[i].volume}const max=Math.max(...sums),min=Math.min(...sums);const profile=sums.map((value,index)=>({index,priceLow:L+step*index,priceHigh:L+step*(index+1),volumeSigned:value,volumeTotal:totals[index],gradientRatio:value>0?(max?value/max:0):(min?value/min:0),isUp:value>0}));const poc=(value:number,label:string):PocBox|null=>{const i=sums.indexOf(value);return i<0?null:{priceLow:L+step*i,priceHigh:L+step*(i+1),label:`${label}: ${totals[i].toLocaleString()}`,volumeTotal:totals[i]}};return {vwapSeries,vwapColor,range:{high:H,low:L,step},bins:profile,positivePoc:poc(max,"+VWAP"),negativePoc:poc(min,"-VWAP"),anchorIndex:last+offset,noVolumeData:bars.reduce((sum,b)=>sum+b.volume,0)<1}}
